# Site settings
title: A coding journey!
header-img: img/home-bg.png
email: anax131@gmail.com
copyright_name: xirinia
description: > # this means to ignore newlines until "baseurl:"
  Web Development 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  xirinia
learn_profile: xirinia
email_username: anax131@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
